spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: cami
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true
  logging:
    level:
      org.hibernate.SQL:DEBUG
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: NW5CX2URDwEwObnH4AZftOhrH9SI2Vp3QFN3AV1NW9--99Khsul2BUGkNw0cRilNF3DFBnyylBfZE7OvRwtOSw
  expiration: 999999